### ISSUE TITLE
todo list parsing failing on lists starting with `*`

### ISSUE THREAD

**Issue by peterbe** [buddys/marktex#1]
Check out [this issue description](https://github.com/mozilla/bedrock/pull/4165#issue-157263456). There's a working todo-list. He's done it like this:

```
TODO:
* [ ] docs
* [ ] unit test suite passing
* [ ] functional test suite passing
* [ ] headless test suite passing
* [ ] containerized firefox + selenium hub integration tests passing
* [x] determine if collectstatic should be run during docker image creation
```

marktex fails to parse this into a todo list.

Here's my debugging:

```
:~/dev/JAVASCRIPT/react-buggy (master *%>)$ cat test.md
Other **things** are working.

TODO:
* [ ] docs
* [ ] unit test suite passing
* [ ] functional test suite passing
* [ ] headless test suite passing
* [ ] containerized firefox + selenium hub integration tests passing
* [x] determine if collectstatic should be run during docker image creation
:~/dev/JAVASCRIPT/react-buggy (master *%>)$ marktex -f test.md

<p>Other <strong>things</strong> are working.</p>
<p>TODO:</p>
<ul>
<li>[ ] docs</li>
<li>[ ] unit test suite passing</li>
<li>[ ] functional test suite passing</li>
<li>[ ] headless test suite passing</li>
<li>[ ] containerized firefox + selenium hub integration tests passing</li>
<li>[x] determine if collectstatic should be run during docker image creation</li>
</ul>
```

If I replace the `*` with a `-` it works:

```
:~/dev/JAVASCRIPT/react-buggy (master *%>)$ cat test-mod.md
Other **things** are working.

TODO:
- [ ] docs
- [ ] unit test suite passing
- [ ] functional test suite passing
- [ ] headless test suite passing
- [ ] containerized firefox + selenium hub integration tests passing
- [x] determine if collectstatic should be run during docker image creation
:~/dev/JAVASCRIPT/react-buggy (master *%>)$ marktex -f test-mod.md


<p>Other <strong>things</strong> are working.</p>
<p>TODO:</p>
<div class="todo">
<div class="todoitem"><span ></span><div>docs</div></div>
<div class="todoitem"><span ></span><div>unit test suite passing</div></div>
<div class="todoitem"><span ></span><div>functional test suite passing</div></div>
<div class="todoitem"><span ></span><div>headless test suite passing</div></div>
<div class="todoitem"><span ></span><div>containerized firefox + selenium hub integration tests passing</div></div>
<div class="todoitem"><span class="checked"></span><div>determine if collectstatic should be run during docker image creation</div></div>
</div>
```

**Comment by harttle** [comment]
I'm sorry this project is no longer maintained. You probably want [showdown](https://github.com/showdownjs/showdown) or [node-gfm](https://github.com/gagle/node-gfm).

I'll appreciate it if you want to contribute and take it over.
